[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "76620388e1ec88675cf6b9def9257370db6cf599"
os = "macos"

    [[GLEW.download]]
    sha256 = "719492a313cf3f44382c85446929972fdd72e0a2005dc1c375323c9f27676d45"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.x86_64-apple-darwin14.tar.gz"
[[GLEW]]
arch = "i686"
git-tree-sha1 = "4ab8a541646d89eb510728a0e4b6d17ef3ea45ea"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "dab2289eda3f2e13339b2701aae180761c60da9ef502f17ecf1e7d4d5c6374e2"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.i686-linux-gnu.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "4068c27c389aaf79ea9972c8b90aefef5be0ddf3"
os = "freebsd"

    [[GLEW.download]]
    sha256 = "658015a138a70d531a74be5f3aec24342fb48924b704a492737d00c0eaba59a6"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[GLEW]]
arch = "powerpc64le"
git-tree-sha1 = "464f271332f201f0e52cbeb002a0c400be3ef21a"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "9c159160731d8a42d1f318d309be12797a2c4858581c2ac64f8e1ec3279dbd61"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "b3c172865febe1e049fd2eaf7c6ebf1426714b5f"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "f860618c8ead5633457272b9980503c4b3102c0e6f0fe9f4eaf64527658e0f54"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.x86_64-linux-musl.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "bb219d09904e0945cd9c740010ef2ece71e05c59"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "5ea7d7bacac1d3d7e105a5cbabd8cb039878cd53fc6b29f26220bc82653682db"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.x86_64-linux-gnu.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "32a0cecf737971e363793b4aa2e21ad7a82c47ad"
os = "windows"

    [[GLEW.download]]
    sha256 = "106427a189f7f7a87fc5e4f1b0ca618f5d5cc86a24aac702bc2f0257ab60ad57"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.x86_64-w64-mingw32.tar.gz"
[[GLEW]]
arch = "aarch64"
git-tree-sha1 = "22ed365e64ae9fe0c627fa38c4284fa50c646143"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "a0dbd08bb1e177438f1099c51e3682cd3cf4ea3e994f4df7b57a8741a6a0e94f"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.aarch64-linux-musl.tar.gz"
[[GLEW]]
arch = "armv7l"
git-tree-sha1 = "596a469346bebbf9e8895337bd72251919bdd33b"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "b95e07b2e223955d8eb2cbe7778aab2740a6f70c1574e6e5530b77bf4958c0ad"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.arm-linux-gnueabihf.tar.gz"
[[GLEW]]
arch = "i686"
git-tree-sha1 = "c545c517fc8395b7bb70d49ed0e3f3c122c5480f"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "0cc56366e4e2d21027c7ce92c8c375e4d2878ff05aa72349d1292c0a5255500c"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.i686-linux-musl.tar.gz"
[[GLEW]]
arch = "armv7l"
git-tree-sha1 = "6ff7f37782bfd8950461c3adb8fb4295579c2501"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "045592202e9e2bcd81b98d144bb146b39787bd3841fe2480ff502c00d35ce7c8"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.arm-linux-musleabihf.tar.gz"
[[GLEW]]
arch = "aarch64"
git-tree-sha1 = "34476b0b5a16332d5e86de7ea7b04083560c6457"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "88f694497b3b50eb33157e2e663276181a872ee42e731e06d2a17bf60594a744"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.aarch64-linux-gnu.tar.gz"
[[GLEW]]
arch = "i686"
git-tree-sha1 = "ba98cea0c616747818a25b99f5b62f33dbc7aa08"
os = "windows"

    [[GLEW.download]]
    sha256 = "8447fec4bcaec2aa44aea040aaa93da5e47e933323a433932066c35e0f29e47d"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+2/GLEW.v2.1.0.i686-w64-mingw32.tar.gz"
